'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmModuleArticle

    '''<summary>
    '''frmMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMaster As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litAdminEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAdminEdit As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBackGroundTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBackGroundTop As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTitleData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTitleData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBodyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBodyText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBodyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBodyImage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSubArticleMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubArticleMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSubArticleGalleryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubArticleGalleryTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSubArticleGallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubArticleGallery As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litNoGalleryImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNoGalleryImages As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBackGroundBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBackGroundBottom As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRightSideImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRightSideImage As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubMenu As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litScripts As Global.System.Web.UI.WebControls.Literal
End Class
