Public Class getCaptchaImage
    Inherits System.Web.UI.Page

    Public Shared words() As String = New String() {"ABACUS", _
"ABACUSES", _
"ABATED", _
"ABATES", _
"ABATING", _
"ABBEYS", _
"ABBOTS", _
"ABDICATE", _
"ABDOMEN", _
"ABDOMENS", _
"ABDUCT", _
"ABDUCTED", _
"ABDUCTS", _
"ABETTED", _
"ABETTING", _
"ABHORRED", _
"ABHORS", _
"ABIDES", _
"ABIDING", _
"ABJECT", _
"ABLAZE", _
"ABLEST", _
"ABOARD", _
"ABODES", _
"ABORTIVE", _
"ABOUND", _
"ABOUNDED", _
"ABOUNDS", _
"ABRASIVE", _
"ABREAST", _
"ABRIDGE", _
"ABRIDGED", _
"ABRIDGES", _
"ABRUPT", _
"ABRUPTER", _
"ABRUPTLY", _
"ABSCESS", _
"ABSCOND", _
"ABSCONDS", _
"ABSENCES", _
"ABSENTED", _
"ABSENTEE", _
"ABSENTS", _
"ABSOLVE", _
"ABSOLVED", _
"ABSOLVES", _
"ABSTAIN", _
"ABSTAINS", _
"ABSTRUSE", _
"ABSURDER", _
"ABSURDLY", _
"ABUNDANT", _
"ABUSER", _
"ABUSERS", _
"ABYSSES", _
"ACADEMY", _
"ACCEDE", _
"ACCEDED", _
"ACCEDES", _
"ACCEDING", _
"ACCENTED", _
"ACCLAIM", _
"ACCLAIMS", _
"ACCOLADE", _
"ACCOST", _
"ACCOSTED", _
"ACCOSTS", _
"ACCREDIT", _
"ACCRUE", _
"ACCRUED", _
"ACCRUES", _
"ACCRUING", _
"ACCUSER", _
"ACCUSERS", _
"ACHING", _
"ACIDITY", _
"ACORNS", _
"ACQUAINT", _
"ACQUIT", _
"ACQUITS", _
"ACREAGE", _
"ACREAGES", _
"ACRIDER", _
"ACRIDEST", _
"ACRIMONY", _
"ACROBAT", _
"ACROBATS", _
"ACRYLIC", _
"ACRYLICS", _
"ACTIVES", _
"ACTIVIST", _
"ACTRESS", _
"ACTUARY", _
"ACUMEN", _
"ACUTELY", _
"ACUTER", _
"ACUTES", _
"ACUTEST", _
"ADAGES", _
"ADAMANT", _
"ADAPTIVE", _
"ADDENDUM", _
"ADDITIVE", _
"ADEPTS", _
"ADHERENT", _
"ADHESION", _
"ADHESIVE", _
"ADJOIN", _
"ADJOINED", _
"ADJOINS", _
"ADJOURN", _
"ADJOURNS", _
"ADJUNCT", _
"ADJUNCTS", _
"ADMIRAL", _
"ADMIRALS", _
"ADMIRED", _
"ADMIRER", _
"ADMIRERS", _
"ADMIRES", _
"ADMIRING", _
"ADMONISH", _
"ADOBES", _
"ADORABLE", _
"ADORED", _
"ADORES", _
"ADORING", _
"ADORNED", _
"ADORNING", _
"ADORNS", _
"ADRIFT", _
"ADROIT", _
"ADROITLY", _
"ADULTERY", _
"ADVERB", _
"ADVERSER", _
"AERIALS", _
"AEROSOL", _
"AEROSOLS", _
"AFFABLE", _
"AFFABLY", _
"AFFINITY", _
"AFFIRM", _
"AFFIRMED", _
"AFFIRMS", _
"AFFIXED", _
"AFFIXES", _
"AFFIXING", _
"AFFLICT", _
"AFFLICTS", _
"AFFLUENT", _
"AFFORDED", _
"AFFORDS", _
"AFFRONT", _
"AFFRONTS", _
"AFIELD", _
"AFLAME", _
"AFLOAT", _
"AFRESH", _
"AGENCIES", _
"AGENDAS", _
"AGHAST", _
"AGILER", _
"AGILEST", _
"AGILITY", _
"AGITATE", _
"AGITATED", _
"AGITATES", _
"AGITATOR", _
"AGNOSTIC", _
"AGONIES", _
"AGROUND", _
"AILING", _
"AILMENT", _
"AILMENTS", _
"AIMLESS", _
"AIRBORNE", _
"AIRFIELD", _
"AIRIER", _
"AIRIEST", _
"AIRING", _
"AIRLINE", _
"AIRLINER", _
"AIRLINES", _
"AIRMAIL", _
"AIRMAILS", _
"AIRPORTS", _
"AIRSTRIP", _
"AIRTIGHT", _
"AISLES", _
"ALARMIST", _
"ALBINO", _
"ALBINOS", _
"ALCOHOLS", _
"ALCOVE", _
"ALCOVES", _
"ALERTED", _
"ALERTING", _
"ALERTS", _
"ALIASED", _
"ALIASING", _
"ALIBIED", _
"ALIBIING", _
"ALIBIS", _
"ALIENATE", _
"ALIENED", _
"ALIENING", _
"ALIGHT", _
"ALIGHTED", _
"ALIGHTS", _
"ALIMONY", _
"ALKALI", _
"ALKALIES", _
"ALKALINE", _
"ALLAYED", _
"ALLAYING", _
"ALLAYS", _
"ALLEGORY", _
"ALLERGY", _
"ALLEYS", _
"ALLIED", _
"ALLOTS", _
"ALLOTTED", _
"ALLOYED", _
"ALLOYING", _
"ALLOYS", _
"ALLUDE", _
"ALLUDED", _
"ALLUDES", _
"ALLUDING", _
"ALLURE", _
"ALLURED", _
"ALLURES", _
"ALLURING", _
"ALLUSION", _
"ALLYING", _
"ALMANAC", _
"ALMANACS", _
"ALMIGHTY", _
"ALMOND", _
"ALMONDS", _
"ALTARS", _
"ALTITUDE", _
"ALTRUISM", _
"AMASSED", _
"AMASSES", _
"AMASSING", _
"AMATEURS", _
"AMBITION", _
"AMBLED", _
"AMBLES", _
"AMBLING", _
"AMBUSH", _
"AMBUSHED", _
"AMBUSHES", _
"AMENABLE", _
"AMENITY", _
"AMETHYST", _
"AMIABLE", _
"AMIABLY", _
"AMICABLE", _
"AMICABLY", _
"AMMONIA", _
"AMNESIA", _
"AMNESTY", _
"AMOEBA", _
"AMOEBAS", _
"AMORAL", _
"AMOROUS", _
"AMOUNTED", _
"AMPERE", _
"AMPERES", _
"AMPLER", _
"AMPLEST", _
"AMPLIFY", _
"AMPUTATE", _
"AMULET", _
"AMULETS", _
"ANALYSTS", _
"ANALYTIC", _
"ANARCHIC", _
"ANATHEMA", _
"ANCESTRY", _
"ANCHOR", _
"ANCHORED", _
"ANCHORS", _
"ANCHOVY", _
"ANCIENTS", _
"ANDROID", _
"ANDROIDS", _
"ANGELIC", _
"ANGERED", _
"ANGERING", _
"ANGERS", _
"ANGLED", _
"ANGLER", _
"ANGLERS", _
"ANGLING", _
"ANGRIER", _
"ANGRIEST", _
"ANGRILY", _
"ANGULAR", _
"ANIMATE", _
"ANIMATED", _
"ANIMATES", _
"ANKLES", _
"ANNALS", _
"ANNEXED", _
"ANNEXES", _
"ANNEXING", _
"ANNOTATE", _
"ANNUALS", _
"ANNUITY", _
"ANNULLED", _
"ANNULS", _
"ANOINT", _
"ANOINTED", _
"ANOINTS", _
"ANTEATER", _
"ANTELOPE", _
"ANTENNA", _
"ANTENNAE", _
"ANTENNAS", _
"ANTHEM", _
"ANTHEMS", _
"ANTHILL", _
"ANTHILLS", _
"ANTHRAX", _
"ANTIBODY", _
"ANTICS", _
"ANTIQUED", _
"ANTIQUES", _
"ANTLER", _
"ANTLERS", _
"ANTONYM", _
"ANTONYMS", _
"ANUSES", _
"ANVILS", _
"ANXIETY", _
"AORTAS", _
"APERTURE", _
"APEXES", _
"APHORISM", _
"APIECE", _
"APLOMB", _
"APOSTLE", _
"APOSTLES", _
"APPAREL", _
"APPARELS", _
"APPEASE", _
"APPEASED", _
"APPEASES", _
"APPETITE", _
"APPLAUD", _
"APPLAUDS", _
"APPLES", _
"APPOSITE", _
"APPRAISE", _
"APRICOT", _
"APRICOTS", _
"APRONS", _
"APTEST", _
"APTITUDE", _
"AQUARIUM", _
"AQUATIC", _
"AQUATICS", _
"AQUEDUCT", _
"ARABLE", _
"ARBITER", _
"ARBITERS", _
"ARCADES", _
"ARCHED", _
"ARCHER", _
"ARCHERS", _
"ARCHERY", _
"ARCHES", _
"ARCHEST", _
"ARCHING", _
"ARCHWAY", _
"ARCHWAYS", _
"ARCING", _
"ARDENT", _
"ARDENTLY", _
"ARDUOUS", _
"ARENAS", _
"ARMAMENT", _
"ARMCHAIR", _
"ARMIES", _
"ARMPIT", _
"ARMPITS", _
"AROMAS", _
"AROMATIC", _
"AROUSE", _
"AROUSED", _
"AROUSES", _
"AROUSING", _
"ARRAIGN", _
"ARRAIGNS", _
"ARRAYED", _
"ARRAYING", _
"ARREARS", _
"ARRIVALS", _
"ARSENAL", _
"ARSENALS", _
"ARSENIC", _
"ARTERIAL", _
"ARTERIES", _
"ARTERY", _
"ARTFUL", _
"ARTIFICE", _
"ARTISAN", _
"ARTISANS", _
"ARTISTRY", _
"ARTWORK", _
"ASBESTOS", _
"ASCENT", _
"ASCENTS", _
"ASCETIC", _
"ASCETICS", _
"ASCRIBE", _
"ASCRIBED", _
"ASCRIBES", _
"ASEXUAL", _
"ASHING", _
"ASHORE", _
"ASHTRAY", _
"ASHTRAYS", _
"ASIDES", _
"ASKANCE", _
"ASPENS", _
"ASPHALT", _
"ASPHALTS", _
"ASPIRANT", _
"ASPIRE", _
"ASPIRED", _
"ASPIRES", _
"ASPIRIN", _
"ASPIRING", _
"ASPIRINS", _
"ASSAIL", _
"ASSAILED", _
"ASSAILS", _
"ASSASSIN", _
"ASSAULTS", _
"ASSENT", _
"ASSENTED", _
"ASSENTS", _
"ASSESSOR", _
"ASSUREDS", _
"ASTEROID", _
"ASTHMA", _
"ASTONISH", _
"ASTOUND", _
"ASTOUNDS", _
"ASTRAY", _
"ASTRIDE", _
"ASTUTE", _
"ASTUTELY", _
"ASTUTER", _
"ASTUTEST", _
"ASYLUM", _
"ASYLUMS", _
"ATHLETE", _
"ATHLETES", _
"ATHLETIC", _
"ATLASES", _
"ATONED", _
"ATONES", _
"ATONING", _
"ATTACHE", _
"ATTACKER", _
"ATTAINED", _
"ATTAINS", _
"ATTEST", _
"ATTESTED", _
"ATTESTS", _
"ATTICS", _
"ATTIRE", _
"ATTIRED", _
"ATTIRES", _
"ATTIRING", _
"ATTUNE", _
"ATTUNED", _
"ATTUNES", _
"ATTUNING", _
"AUBURN", _
"AUCTION", _
"AUCTIONS", _
"AUDACITY", _
"AUDIBLES", _
"AUDIBLY", _
"AUDIOS", _
"AUDITED", _
"AUDITING", _
"AUDITION", _
"AUDITOR", _
"AUDITORS", _
"AUDITORY", _
"AUDITS", _
"AUGMENT", _
"AUGMENTS", _
"AUGUST", _
"AUGUSTER", _
"AUSTERE", _
"AUSTERER", _
"AUTHORED", _
"AUTOCRAT", _
"AUTONOMY", _
"AUTOPSY", _
"AUTUMNAL", _
"AUTUMNS", _
"AVAILED", _
"AVAILING", _
"AVAILS", _
"AVARICE", _
"AVENGE", _
"AVENGED", _
"AVENGES", _
"AVENGING", _
"AVENUE", _
"AVENUES", _
"AVERAGED", _
"AVERAGES", _
"AVERSE", _
"AVERSION", _
"AVERTED", _
"AVERTING", _
"AVERTS", _
"AVIATION", _
"AVIATOR", _
"AVIATORS", _
"AVOCADO", _
"AVOCADOS", _
"AVOWAL", _
"AVOWALS", _
"AVOWED", _
"AVOWING", _
"AWAKEN", _
"AWAKENED", _
"AWAKENS", _
"AWAKES", _
"AWAKING", _
"AWESOME", _
"AWFULLER", _
"AWHILE", _
"AWNING", _
"AWNINGS", _
"AWOKEN", _
"AZALEA", _
"AZALEAS", _
"AZURES", _
"BABBLE", _
"BABBLED", _
"BABBLES", _
"BABBLING", _
"BABIED", _
"BABIER", _
"BABIEST", _
"BABOON", _
"BABOONS", _
"BABYING", _
"BABYISH", _
"BACHELOR", _
"BACKER", _
"BACKERS", _
"BACKFIRE", _
"BACKHAND", _
"BACKINGS", _
"BACKLASH", _
"BACKLOGS", _
"BACKPACK", _
"BACKSIDE", _
"BADDER", _
"BADDEST", _
"BADGER", _
"BADGERED", _
"BADGERS", _
"BADGES", _
"BADNESS", _
"BAGELS", _
"BAGGED", _
"BAGGIER", _
"BAGGIEST", _
"BAGGING", _
"BAILED", _
"BAILING", _
"BAITED", _
"BAITING", _
"BAKERIES", _
"BAKERS", _
"BAKERY", _
"BALCONY", _
"BALDED", _
"BALDER", _
"BALDEST", _
"BALDING", _
"BALDNESS", _
"BALING", _
"BALLAD", _
"BALLADS", _
"BALLAST", _
"BALLASTS", _
"BALLED", _
"BALLETS", _
"BALLING", _
"BALLOON", _
"BALLOONS", _
"BALLOTED", _
"BALLOTS", _
"BALLROOM", _
"BALMIER", _
"BALMIEST", _
"BALONEY", _
"BAMBOO", _
"BAMBOOS", _
"BANDAGE", _
"BANDAGED", _
"BANDAGES", _
"BANDED", _
"BANDIED", _
"BANDIER", _
"BANDIES", _
"BANDIEST", _
"BANDING", _
"BANDIT", _
"BANDITS", _
"BANDYING", _
"BANGED", _
"BANGING", _
"BANISH", _
"BANISHED", _
"BANISHES", _
"BANISTER", _
"BANJOS", _
"BANKED", _
"BANKER", _
"BANKERS", _
"BANKING", _
"BANKNOTE", _
"BANNERS", _
"BANQUET", _
"BANQUETS", _
"BANTER", _
"BANTERED", _
"BANTERS", _
"BAPTISM", _
"BAPTISMS", _
"BARBARIC", _
"BARBECUE", _
"BARBED", _
"BARBER", _
"BARBERED", _
"BARBERS", _
"BARBING", _
"BAREBACK", _
"BAREFOOT", _
"BAREST", _
"BARGAINS", _
"BARGED", _
"BARGES", _
"BARGING", _
"BARING", _
"BARITONE", _
"BARLEY", _
"BARMAN", _
"BARNACLE", _
"BARNYARD", _
"BARONS", _
"BARRAGE", _
"BARRAGED", _
"BARRAGES", _
"BARRELS", _
"BARREN", _
"BARRENER", _
"BARRENS", _
"BARRETTE", _
"BARRINGS", _
"BARTER", _
"BARTERED", _
"BARTERS", _
"BASEBALL", _
"BASELINE", _
"BASEST", _
"BASHFUL", _
"BASINS", _
"BASKED", _
"BASKETS", _
"BASKING", _
"BASSOON", _
"BASSOONS", _
"BASTED", _
"BASTES", _
"BASTING", _
"BATCHED", _
"BATCHES", _
"BATCHING", _
"BATHED", _
"BATHES", _
"BATHING", _
"BATHTUB", _
"BATHTUBS", _
"BATONS", _
"BATSMAN", _
"BATTED", _
"BATTER", _
"BATTERED", _
"BATTERS", _
"BATTING", _
"BATTLED", _
"BATTLES", _
"BATTLING", _
"BAWDIER", _
"BAWDIEST", _
"BAWLED", _
"BAWLING", _
"BAYING", _
"BAYONET", _
"BAYONETS", _
"BAYOUS", _
"BAZAAR", _
"BAZAARS", _
"BEACHED", _
"BEACHES", _
"BEACHING", _
"BEACON", _
"BEACONS", _
"BEADED", _
"BEADIER", _
"BEADIEST", _
"BEADING", _
"BEAGLE", _
"BEAGLES", _
"BEAKED", _
"BEAKER", _
"BEAKERS", _
"BEAMED", _
"BEAMING", _
"BEANED", _
"BEANING", _
"BEARABLE", _
"BEARER", _
"BEARERS", _
"BEARINGS", _
"BEATER", _
"BEATERS", _
"BEAUTIES", _
"BEAUTIFY", _
"BEAVER", _
"BEAVERED", _
"BEAVERS", _
"BECKON", _
"BECKONED", _
"BECKONS", _
"BEDBUG", _
"BEDBUGS", _
"BEDDED", _
"BEDDER", _
"BEDDING", _
"BEDLAM", _
"BEDLAMS", _
"BEDROCK", _
"BEDROCKS", _
"BEDROOMS", _
"BEDSIDE", _
"BEDSIDES", _
"BEDTIME", _
"BEDTIMES", _
"BEECHES", _
"BEEFED", _
"BEEFIER", _
"BEEFIEST", _
"BEEFING", _
"BEEHIVE", _
"BEEHIVES", _
"BEEPER", _
"BEESWAX", _
"BEETLE", _
"BEETLED", _
"BEETLES", _
"BEETLING", _
"BEEVES", _
"BEFALL", _
"BEFALLEN", _
"BEFALLS", _
"BEFELL", _
"BEFITS", _
"BEFITTED", _
"BEFRIEND", _
"BEGGAR", _
"BEGGARED", _
"BEGGARS", _
"BEGGED", _
"BEGGING", _
"BEGRUDGE", _
"BEGUILE", _
"BEGUILED", _
"BEGUILES", _
"BEHALVES", _
"BEHEAD", _
"BEHEADED", _
"BEHEADS", _
"BEHELD", _
"BEHINDS", _
"BEHOLD", _
"BEHOLDER", _
"BEHOLDS", _
"BELATED", _
"BELCHED", _
"BELCHES", _
"BELCHING", _
"BELFRIES", _
"BELFRY", _
"BELIED", _
"BELIES", _
"BELITTLE", _
"BELLBOY", _
"BELLBOYS", _
"BELLED", _
"BELLHOP", _
"BELLHOPS", _
"BELLIED", _
"BELLIES", _
"BELLING", _
"BELLOW", _
"BELLOWED", _
"BELLOWS", _
"BELLYING", _
"BELOVEDS", _
"BELTED", _
"BELTING", _
"BELYING", _
"BEMOAN", _
"BEMOANED", _
"BEMOANS", _
"BEMUSE", _
"BEMUSED", _
"BEMUSES", _
"BEMUSING", _
"BENCHED", _
"BENCHES", _
"BENCHING", _
"BENDER", _
"BENIGN", _
"BEQUEATH", _
"BEQUEST", _
"BEQUESTS", _
"BEREAVE", _
"BEREAVED", _
"BEREAVES", _
"BEREFT", _
"BERETS", _
"BERRIED", _
"BERRIES", _
"BERRYING", _
"BERSERK", _
"BERTHED", _
"BERTHING", _
"BERTHS", _
"BESEECH", _
"BESETS", _
"BESIEGE", _
"BESIEGED", _
"BESIEGES", _
"BESOUGHT", _
"BESTED", _
"BESTIAL", _
"BESTING", _
"BESTOW", _
"BESTOWED", _
"BESTOWS", _
"BETCHA", _
"BETRAY", _
"BETRAYAL", _
"BETRAYED", _
"BETRAYS", _
"BETTERED", _
"BETTERS", _
"BETTOR", _
"BETTORS", _
"BEVERAGE", _
"BEWARED", _
"BEWARES", _
"BEWARING", _
"BEWILDER", _
"BEWITCH", _
"BICKER", _
"BICKERED", _
"BICKERS", _
"BICYCLED", _
"BIDDEN", _
"BIDING", _
"BIENNIAL", _
"BIFOCALS", _
"BIGAMIST", _
"BIGAMOUS", _
"BIGAMY", _
"BIGOTS", _
"BIKING", _
"BIKINI", _
"BIKINIS", _
"BILLED", _
"BILLING", _
"BILLOW", _
"BILLOWED", _
"BILLOWS", _
"BINARIES", _
"BINDER", _
"BINDERS", _
"BINDINGS", _
"BINNED", _
"BINNING", _
"BINOMIAL", _
"BIPEDS", _
"BIPLANE", _
"BIPLANES", _
"BIRCHED", _
"BIRCHES", _
"BIRCHING", _
"BIRDCAGE", _
"BIRDED", _
"BIRDING", _
"BIRTHED", _
"BIRTHING", _
"BIRTHS", _
"BISECT", _
"BISECTED", _
"BISECTS", _
"BISHOPS", _
"BITTERER", _
"BITTERLY", _
"BLABBED", _
"BLABBING", _
"BLACKED", _
"BLACKEN", _
"BLACKENS", _
"BLACKER", _
"BLACKEST", _
"BLACKING", _
"BLACKOUT", _
"BLACKTOP", _
"BLADDER", _
"BLADDERS", _
"BLAMER", _
"BLANCH", _
"BLANCHED", _
"BLANCHES", _
"BLANDER", _
"BLANDEST", _
"BLANKED", _
"BLANKER", _
"BLANKEST", _
"BLANKETS", _
"BLANKING", _
"BLANKLY", _
"BLARED", _
"BLARES", _
"BLARING", _
"BLASTER", _
"BLAZED", _
"BLAZER", _
"BLAZERS", _
"BLAZES", _
"BLAZING", _
"BLEACH", _
"BLEACHED", _
"BLEACHES", _
"BLEAKER", _
"BLEAKEST", _
"BLEARIER", _
"BLEARY", _
"BLEATED", _
"BLEATING", _
"BLEATS", _
"BLEEDING", _
"BLEEDS", _
"BLEMISH", _
"BLENDED", _
"BLENDING", _
"BLENDS", _
"BLIGHT", _
"BLIGHTED", _
"BLIGHTS", _
"BLIMPS", _
"BLINDED", _
"BLINDER", _
"BLINDEST", _
"BLINDING", _
"BLINDS", _
"BLINKED", _
"BLINKER", _
"BLINKERS", _
"BLINKING", _
"BLINKS", _
"BLISSFUL", _
"BLISTER", _
"BLISTERS", _
"BLITHE", _
"BLITHELY", _
"BLITHER", _
"BLITHEST", _
"BLITZED", _
"BLITZES", _
"BLITZING", _
"BLIZZARD", _
"BLOBBED", _
"BLOBBING", _
"BLOCKADE", _
"BLOCKAGE", _
"BLOGGED", _
"BLOGGER", _
"BLOGGERS", _
"BLOGGING", _
"BLONDE", _
"BLONDER", _
"BLONDES", _
"BLONDEST", _
"BLONDS", _
"BLOODED", _
"BLOODIED", _
"BLOODIER", _
"BLOODIES", _
"BLOODING", _
"BLOODS", _
"BLOOMED", _
"BLOOMING", _
"BLOOMS", _
"BLOSSOM", _
"BLOSSOMS", _
"BLOTCH", _
"BLOTCHED", _
"BLOTCHES", _
"BLOTTED", _
"BLOTTER", _
"BLOTTERS", _
"BLOTTING", _
"BLOUSE", _
"BLOUSED", _
"BLOUSES", _
"BLOUSING", _
"BLOWOUT", _
"BLOWOUTS", _
"BLUBBER", _
"BLUBBERS", _
"BLUDGEON", _
"BLUEBELL", _
"BLUEBIRD", _
"BLUEST", _
"BLUFFED", _
"BLUFFER", _
"BLUFFEST", _
"BLUFFING", _
"BLUFFS", _
"BLUING", _
"BLUNDER", _
"BLUNDERS", _
"BLUNTED", _
"BLUNTER", _
"BLUNTEST", _
"BLUNTING", _
"BLUNTLY", _
"BLUNTS", _
"BLURRED", _
"BLURRING", _
"BLURTED", _
"BLURTING", _
"BLURTS", _
"BLUSHED", _
"BLUSHES", _
"BLUSHING", _
"BLUSTER", _
"BLUSTERS", _
"BOARDED", _
"BOARDER", _
"BOARDERS", _
"BOARDING", _
"BOASTED", _
"BOASTFUL", _
"BOASTING", _
"BOASTS", _
"BOATED", _
"BOATING", _
"BOBBED", _
"BOBBIN", _
"BOBBING", _
"BOBBINS", _
"BOBCAT", _
"BOBCATS", _
"BOBSLED", _
"BOBSLEDS", _
"BODICE", _
"BODICES", _
"BODILY", _
"BODING", _
"BODYWORK", _
"BOGGLED", _
"BOGGLING", _
"BOILER", _
"BOILERS", _
"BOLDER", _
"BOLDEST", _
"BOLDLY", _
"BOLDNESS", _
"BOLOGNA", _
"BOLSTER", _
"BOLSTERS", _
"BOLTED", _
"BOLTING", _
"BOMBARD", _
"BOMBARDS", _
"BOMBER", _
"BOMBERS", _
"BOMBINGS", _
"BONDAGE", _
"BONDED", _
"BONDING", _
"BONFIRE", _
"BONFIRES", _
"BONIER", _
"BONIEST", _
"BONING", _
"BONNET", _
"BONNETS", _
"BONUSES", _
"BOOING", _
"BOOKCASE", _
"BOOKEND", _
"BOOKENDS", _
"BOOKINGS", _
"BOOKLETS", _
"BOOKMARK", _
"BOOKWORM", _
"BOOMED", _
"BOOMING", _
"BOORISH", _
"BOOSTED", _
"BOOSTER", _
"BOOSTERS", _
"BOOSTING", _
"BOOSTS", _
"BOOTED", _
"BOOTEE", _
"BOOTEES", _
"BOOTHS", _
"BOOTIES", _
"BOOTING", _
"BOOTLEG", _
"BOOTLEGS", _
"BORDERED", _
"BORDERS", _
"BORINGLY", _
"BOROUGH", _
"BOROUGHS", _
"BOSOMS", _
"BOSSED", _
"BOSSES", _
"BOSSIER", _
"BOSSIEST", _
"BOSSING", _
"BOTANIST", _
"BOTANY", _
"BOTCHED", _
"BOTCHES", _
"BOTCHING", _
"BOTTLED", _
"BOTTLING", _
"BOTTOMED", _
"BOTTOMS", _
"BOUGHS", _
"BOULDER", _
"BOULDERS", _
"BOUNCED", _
"BOUNCES", _
"BOUNCING", _
"BOUNDED", _
"BOUNDING", _
"BOUNTIES", _
"BOUNTY", _
"BOUQUET", _
"BOUQUETS", _
"BOURBON", _
"BOUTIQUE", _
"BOVINE", _
"BOVINES", _
"BOWELS", _
"BOWING", _
"BOWLED", _
"BOWLER", _
"BOWLING", _
"BOXCAR", _
"BOXCARS", _
"BOXERS", _
"BOXING", _
"BOYCOTT", _
"BOYCOTTS", _
"BOYHOOD", _
"BOYHOODS", _
"BOYISH", _
"BRACED", _
"BRACELET", _
"BRACES", _
"BRACING", _
"BRACKISH", _
"BRAGGART", _
"BRAGGED", _
"BRAGGING", _
"BRAIDED", _
"BRAIDING", _
"BRAIDS", _
"BRAINED", _
"BRAINIER", _
"BRAINING", _
"BRAINY", _
"BRAISE", _
"BRAISED", _
"BRAISES", _
"BRAISING", _
"BRAKED", _
"BRAKING", _
"BRANCHED", _
"BRANDIED", _
"BRANDIES", _
"BRANDISH", _
"BRANDY", _
"BRASHER", _
"BRASHEST", _
"BRASSES", _
"BRASSIER", _
"BRASSY", _
"BRAVADO", _
"BRAVED", _
"BRAVELY", _
"BRAVER", _
"BRAVERY", _
"BRAVES", _
"BRAVEST", _
"BRAVING", _
"BRAVOS", _
"BRAWLED", _
"BRAWLING", _
"BRAWLS", _
"BRAWNIER", _
"BRAWNY", _
"BRAYED", _
"BRAYING", _
"BRAZEN", _
"BRAZENED", _
"BRAZENS", _
"BRAZIER", _
"BRAZIERS", _
"BREACHED", _
"BREACHES", _
"BREADED", _
"BREADING", _
"BREADS", _
"BREADTH", _
"BREADTHS", _
"BREATHER", _
"BREATHS", _
"BREEDER", _
"BREEDERS", _
"BREEZED", _
"BREEZES", _
"BREEZIER", _
"BREEZING", _
"BREEZY", _
"BREVITY", _
"BREWED", _
"BREWERY", _
"BREWING", _
"BRIBED", _
"BRIBERY", _
"BRIBES", _
"BRIBING", _
"BRICKED", _
"BRICKING", _
"BRIDAL", _
"BRIDALS", _
"BRIDES", _
"BRIDGED", _
"BRIDGING", _
"BRIDLE", _
"BRIDLED", _
"BRIDLES", _
"BRIDLING", _
"BRIEFED", _
"BRIEFER", _
"BRIEFEST", _
"BRIEFING", _
"BRIEFS", _
"BRIGADES", _
"BRIGHTEN", _
"BRIMMED", _
"BRIMMING", _
"BRINIER", _
"BRINIEST", _
"BRINKS", _
"BRISKED", _
"BRISKER", _
"BRISKEST", _
"BRISKING", _
"BRISKLY", _
"BRISKS", _
"BRISTLE", _
"BRISTLED", _
"BRISTLES", _
"BRITCHES", _
"BRITTLE", _
"BRITTLER", _
"BROACH", _
"BROACHED", _
"BROACHES", _
"BROADEN", _
"BROADENS", _
"BROADER", _
"BROADEST", _
"BROADS", _
"BROCADE", _
"BROCADED", _
"BROCADES", _
"BROCCOLI", _
"BROCHURE", _
"BROILED", _
"BROILER", _
"BROILERS", _
"BROILING", _
"BROILS", _
"BROKER", _
"BROKERED", _
"BROKERS", _
"BRONCO", _
"BRONCOS", _
"BRONZE", _
"BRONZED", _
"BRONZES", _
"BRONZING", _
"BROOCH", _
"BROOCHES", _
"BROODED", _
"BROODING", _
"BROODS", _
"BROOKED", _
"BROOKING", _
"BROOKS", _
"BROOMS", _
"BROTHS", _
"BROWBEAT", _
"BROWNED", _
"BROWNER", _
"BROWNEST", _
"BROWNIE", _
"BROWNIES", _
"BROWNING", _
"BROWNS", _
"BRUISE", _
"BRUISED", _
"BRUISES", _
"BRUISING", _
"BRUNCH", _
"BRUNCHED", _
"BRUNCHES", _
"BRUNETTE", _
"BRUSHED", _
"BRUSHES", _
"BRUSHING", _
"BRUSQUE", _
"BRUSQUER", _
"BRUTALLY", _
"BRUTES", _
"BRUTISH", _
"BUBBLED", _
"BUBBLES", _
"BUBBLIER", _
"BUBBLING", _
"BUBBLY", _
"BUCKED", _
"BUCKETED", _
"BUCKETS", _
"BUCKING", _
"BUCKLE", _
"BUCKLED", _
"BUCKLES", _
"BUCKLING", _
"BUDDED", _
"BUDDIES", _
"BUDDING", _
"BUDGED", _
"BUDGES", _
"BUDGETED", _
"BUDGETS", _
"BUDGING", _
"BUFFALO", _
"BUFFED", _
"BUFFET", _
"BUFFETED", _
"BUFFETS", _
"BUFFING", _
"BUFFOON", _
"BUFFOONS", _
"BUGGED", _
"BUGGIER", _
"BUGGIES", _
"BUGGIEST", _
"BUGGING", _
"BUGLED", _
"BUGLER", _
"BUGLERS", _
"BUGLES", _
"BUGLING", _
"BUILDER", _
"BUILDERS", _
"BULBOUS", _
"BULGED", _
"BULGES", _
"BULGING", _
"BULKED", _
"BULKIER", _
"BULKIEST", _
"BULKING", _
"BULLDOG", _
"BULLDOGS", _
"BULLDOZE", _
"BULLED", _
"BULLFROG", _
"BULLIED", _
"BULLIES", _
"BULLING", _
"BULLION", _
"BULLYING", _
"BUMMED", _
"BUMMER", _
"BUMMEST", _
"BUMMING", _
"BUMPED", _
"BUMPER", _
"BUMPERS", _
"BUMPIER", _
"BUMPIEST", _
"BUMPING", _
"BUNCHED", _
"BUNCHES", _
"BUNCHING", _
"BUNDLED", _
"BUNDLES", _
"BUNDLING", _
"BUNGALOW", _
"BUNGLE", _
"BUNGLED", _
"BUNGLER", _
"BUNGLERS", _
"BUNGLES", _
"BUNGLING", _
"BUNION", _
"BUNIONS", _
"BUNKED", _
"BUNKER", _
"BUNKERS", _
"BUNKING", _
"BUNNIES", _
"BUOYANCY", _
"BUOYANT", _
"BUOYED", _
"BUOYING", _
"BURBLE", _
"BURBLED", _
"BURBLES", _
"BURBLING", _
"BURDENED", _
"BURDENS", _
"BUREAU", _
"BUREAUS", _
"BURGER", _
"BURGERS", _
"BURGLAR", _
"BURGLARS", _
"BURGLARY", _
"BURGLE", _
"BURIAL", _
"BURIALS", _
"BURLAP", _
"BURLIER", _
"BURLIEST", _
"BURNER", _
"BURNERS", _
"BURNISH", _
"BURPED", _
"BURPING", _
"BURRED", _
"BURRING", _
"BURROS", _
"BURROW", _
"BURROWED", _
"BURROWS", _
"BURSAR", _
"BUSHED", _
"BUSHEL", _
"BUSHELS", _
"BUSHES", _
"BUSHIER", _
"BUSHIEST", _
"BUSHING", _
"BUSIED", _
"BUSIER", _
"BUSIES", _
"BUSIEST", _
"BUSILY", _
"BUSTED", _
"BUSTING", _
"BUSTLE", _
"BUSTLED", _
"BUSTLES", _
"BUSTLING", _
"BUSYBODY", _
"BUSYING", _
"BUTCHER", _
"BUTCHERS", _
"BUTCHERY", _
"BUTLER", _
"BUTLERS", _
"BUTTED", _
"BUTTERED", _
"BUTTERS", _
"BUTTERY", _
"BUTTES", _
"BUTTING", _
"BUTTOCK", _
"BUTTOCKS", _
"BUTTONED", _
"BUTTRESS", _
"BUZZARD", _
"BUZZARDS", _
"BUZZED", _
"BUZZER", _
"BUZZERS", _
"BUZZES", _
"BUZZING", _
"BYGONE", _
"BYGONES", _
"BYPASSED", _
"BYPASSES", _
"BYWAYS", _
"CABARET", _
"CABARETS", _
"CABBAGES", _
"CABBED", _
"CABBING", _
"CABINETS", _
"CABINS", _
"CABOOSE", _
"CABOOSES", _
"CACAOS", _
"CACHED", _
"CACHES", _
"CACHING", _
"CACKLE", _
"CACKLED", _
"CACKLES", _
"CACKLING", _
"CACTUS", _
"CADDIE", _
"CADDIED", _
"CADDIES", _
"CADDYING", _
"CADENCE", _
"CADENCES", _
"CADETS", _
"CAGIER", _
"CAGIEST", _
"CAGING", _
"CAJOLE", _
"CAJOLED", _
"CAJOLES", _
"CAJOLING", _
"CAKING", _
"CALAMITY", _
"CALCIUM", _
"CALCULI", _
"CALICO", _
"CALICOES", _
"CALLABLE", _
"CALLERS", _
"CALLINGS", _
"CALLOUS", _
"CALLOW", _
"CALLUS", _
"CALLUSED", _
"CALLUSES", _
"CALMED", _
"CALMER", _
"CALMEST", _
"CALMING", _
"CALMLY", _
"CALMNESS", _
"CALORIE", _
"CALORIES", _
"CALVES", _
"CAMELS", _
"CAMEOS", _
"CAMPED", _
"CAMPER", _
"CAMPERS", _
"CAMPING", _
"CAMPUSES", _
"CANALS", _
"CANARIES", _
"CANARY", _
"CANCERS", _
"CANDID", _
"CANDIDLY", _
"CANDIED", _
"CANDIES", _
"CANDLE", _
"CANDLED", _
"CANDLES", _
"CANDLING", _
"CANDYING", _
"CANINE", _
"CANINES", _
"CANING", _
"CANISTER", _
"CANKER", _
"CANKERED", _
"CANKERS", _
"CANNED", _
"CANNERY", _
"CANNIBAL", _
"CANNIER", _
"CANNIEST", _
"CANNING", _
"CANNON", _
"CANNONED", _
"CANNONS", _
"CANOED", _
"CANOEING", _
"CANOES", _
"CANONS", _
"CANOPIED", _
"CANOPIES", _
"CANOPY", _
"CANTEEN", _
"CANTEENS", _
"CANTER", _
"CANTERED", _
"CANTERS", _
"CANVAS", _
"CANVASED", _
"CANVASES", _
"CANVASS", _
"CANYON", _
"CANYONS", _
"CAPABLY", _
"CAPERED", _
"CAPERING", _
"CAPERS", _
"CAPPED", _
"CAPPING", _
"CAPRICE", _
"CAPRICES", _
"CAPSIZE", _
"CAPSIZED", _
"CAPSIZES", _
"CAPSULE", _
"CAPSULED", _
"CAPSULES", _
"CAPTAINS", _
"CAPTION", _
"CAPTIONS", _
"CAPTIVE", _
"CAPTIVES", _
"CAPTOR", _
"CAPTORS", _
"CARAMEL", _
"CARAMELS", _
"CARATS", _
"CARAVAN", _
"CARAVANS", _
"CARBONS", _
"CARCASS", _
"CARDED", _
"CARDIAC", _
"CARDIGAN", _
"CARDINAL", _
"CARDING", _
"CAREERED", _
"CAREFREE", _
"CARESS", _
"CARESSED", _
"CARESSES", _
"CARGOES", _
"CARIBOU", _
"CARIBOUS", _
"CARNAGE", _
"CARNAL", _
"CARNIVAL", _
"CAROLS", _
"CAROUSE", _
"CAROUSED", _
"CAROUSES", _
"CARPED", _
"CARPETED", _
"CARPETS", _
"CARPING", _
"CARRIERS", _
"CARRION", _
"CARTED", _
"CARTEL", _
"CARTELS", _
"CARTING", _
"CARTON", _
"CARTONS", _
"CARVED", _
"CARVES", _
"CARVING", _
"CASCADE", _
"CASCADED", _
"CASCADES", _
"CASHED", _
"CASHES", _
"CASHEW", _
"CASHEWS", _
"CASHIER", _
"CASHIERS", _
"CASHING", _
"CASHMERE", _
"CASINGS", _
"CASINO", _
"CASINOS", _
"CASKET", _
"CASKETS", _
"CASTAWAY", _
"CASTER", _
"CASTERS", _
"CASTES", _
"CASTINGS", _
"CASTLED", _
"CASTLES", _
"CASTLING", _
"CASTOFF", _
"CASTOFFS", _
"CASTRATE", _
"CASUALLY", _
"CASUALS", _
"CASUALTY", _
"CATAPULT", _
"CATARACT", _
"CATCALL", _
"CATCALLS", _
"CATCHIER", _
"CATCHY", _
"CATERER", _
"CATERERS", _
"CATFISH", _
"CATNAP", _
"CATNAPS", _
"CATNIP", _
"CATWALK", _
"CATWALKS", _
"CAUCUS", _
"CAUCUSED", _
"CAUCUSES", _
"CAULKED", _
"CAULKING", _
"CAULKS", _
"CAUSEWAY", _
"CAUSTIC", _
"CAUSTICS", _
"CAUTIONS", _
"CAUTIOUS", _
"CAVALIER", _
"CAVALRY", _
"CAVEATS", _
"CAVERN", _
"CAVERNS", _
"CAVIAR", _
"CAVING", _
"CAVITIES", _
"CAVITY", _
"CAVORT", _
"CAVORTED", _
"CAVORTS", _
"CAWING", _
"CEDARS", _
"CEDING", _
"CEILINGS", _
"CELERY", _
"CELIBACY", _
"CELIBATE", _
"CELLAR", _
"CELLARS", _
"CELLIST", _
"CELLISTS", _
"CELLOS", _
"CEMENT", _
"CEMENTED", _
"CEMENTS", _
"CEMETERY", _
"CENSURE", _
"CENSURED", _
"CENSURES", _
"CENSUS", _
"CENSUSED", _
"CENSUSES", _
"CENTRALS", _
"CERAMIC", _
"CEREAL", _
"CEREALS", _
"CEREBRAL", _
"CERTIFY", _
"CERVICAL", _
"CHAFED", _
"CHAFES", _
"CHAFFED", _
"CHAFFING", _
"CHAFFS", _
"CHAFING", _
"CHAGRIN", _
"CHAGRINS", _
"CHAINED", _
"CHAINING", _
"CHAINSAW", _
"CHAIRED", _
"CHAIRING", _
"CHAIRMEN", _
"CHALET", _
"CHALETS", _
"CHALICE", _
"CHALICES", _
"CHALKED", _
"CHALKIER", _
"CHALKING", _
"CHALKS", _
"CHALKY", _
"CHAMBERS", _
"CHAMPED", _
"CHAMPING", _
"CHAMPS", _
"CHANCED", _
"CHANCING", _
"CHANTED", _
"CHANTING", _
"CHANTS", _
"CHAPELS", _
"CHAPLAIN", _
"CHAPPED", _
"CHAPPING", _
"CHARCOAL", _
"CHARGER", _
"CHARIOT", _
"CHARIOTS", _
"CHARISMA", _
"CHARRED", _
"CHARRING", _
"CHARTED", _
"CHARTERS", _
"CHARTING", _
"CHASMS", _
"CHASSIS", _
"CHASTE", _
"CHASTEN", _
"CHASTENS", _
"CHASTER", _
"CHASTEST", _
"CHASTISE", _
"CHASTITY", _
"CHATTER", _
"CHATTERS", _
"CHATTIER", _
"CHATTY", _
"CHEAPEN", _
"CHEAPENS", _
"CHECKERS", _
"CHECKOUT", _
"CHECKUP", _
"CHECKUPS", _
"CHEEKED", _
"CHEEKING", _
"CHEEKS", _
"CHEEPED", _
"CHEEPING", _
"CHEEPS", _
"CHEERED", _
"CHEERIER", _
"CHEERING", _
"CHEERY", _
"CHEESED", _
"CHEESES", _
"CHEESING", _
"CHEETAH", _
"CHEETAHS", _
"CHERISH", _
"CHERRIES", _
"CHERRY", _
"CHERUB", _
"CHERUBIM", _
"CHERUBS", _
"CHESTS", _
"CHEWIER", _
"CHEWIEST", _
"CHICER", _
"CHICEST", _
"CHICKS", _
"CHIDED", _
"CHIDES", _
"CHIDING", _
"CHIEFER", _
"CHIEFEST", _
"CHIEFLY", _
"CHIEFS", _
"CHILLED", _
"CHILLER", _
"CHILLEST", _
"CHILLIER", _
"CHILLING", _
"CHILLS", _
"CHILLY", _
"CHIMED", _
"CHIMES", _
"CHIMING", _
"CHIMNEY", _
"CHIMNEYS", _
"CHIMPS", _
"CHINKED", _
"CHINKING", _
"CHINKS", _
"CHINNED", _
"CHINNING", _
"CHINTZ", _
"CHIPMUNK", _
"CHIPPED", _
"CHIPPER", _
"CHIPPERS", _
"CHIPPING", _
"CHIRPED", _
"CHIRPING", _
"CHIRPS", _
"CHISEL", _
"CHISELS", _
"CHIVALRY", _
"CHLORINE", _
"CHOICER", _
"CHOICEST", _
"CHOIRS", _
"CHOKED", _
"CHOKES", _
"CHOKING", _
"CHOLERA", _
"CHOOSIER", _
"CHOOSY", _
"CHOPPER", _
"CHOPPERS", _
"CHOPPIER", _
"CHOPPY", _
"CHORALS", _
"CHORDS", _
"CHORES", _
"CHORTLE", _
"CHORTLED", _
"CHORTLES", _
"CHORUSED", _
"CHORUSES", _
"CHOWDER", _
"CHOWDERS", _
"CHOWED", _
"CHOWING", _
"CHRISTEN", _
"CHROME", _
"CHROMED", _
"CHROMES", _
"CHROMING", _
"CHROMIUM", _
"CHRONIC", _
"CHUBBIER", _
"CHUBBY", _
"CHUCKLE", _
"CHUCKLED", _
"CHUCKLES", _
"CHUGGED", _
"CHUGGING", _
"CHUMMED", _
"CHUMMIER", _
"CHUMMING", _
"CHUMMY", _
"CHUNKIER", _
"CHUNKY", _
"CHURNED", _
"CHURNING", _
"CHURNS", _
"CHUTES", _
"CIDERS", _
"CIGARS", _
"CINCHED", _
"CINCHES", _
"CINCHING", _
"CINDER", _
"CINDERED", _
"CINDERS", _
"CINEMAS", _
"CINNAMON", _
"CIPHER", _
"CIPHERED", _
"CIPHERS", _
"CIRCLED", _
"CIRCLING", _
"CIRCUS", _
"CIRCUSES", _
"CISTERN", _
"CISTERNS", _
"CITATION", _
"CITRIC", _
"CITRUS", _
"CITRUSES", _
"CIVICS", _
"CIVILITY", _
"CLACKED", _
"CLACKING", _
"CLACKS", _
"CLAMBER", _
"CLAMBERS", _
"CLAMMED", _
"CLAMMIER", _
"CLAMMING", _
"CLAMMY", _
"CLAMPED", _
"CLAMPING", _
"CLAMPS", _
"CLANGED", _
"CLANGING", _
"CLANGS", _
"CLANKED", _
"CLANKING", _
"CLANKS", _
"CLAPPED", _
"CLAPPER", _
"CLAPPERS", _
"CLAPPING", _
"CLAPTRAP", _
"CLARET", _
"CLARINET", _
"CLASHED", _
"CLASHING", _
"CLASPED", _
"CLASPING", _
"CLASPS", _
"CLASSY", _
"CLATTER", _
"CLATTERS", _
"CLAWED", _
"CLAWING", _
"CLEANSE", _
"CLEANSED", _
"CLEANSER", _
"CLEANSES", _
"CLEATS", _
"CLEAVAGE", _
"CLEAVE", _
"CLEAVED", _
"CLEAVER", _
"CLEAVERS", _
"CLEAVES", _
"CLEAVING", _
"CLEFTS", _
"CLEMENCY", _
"CLENCH", _
"CLENCHED", _
"CLENCHES", _
"CLERGIES", _
"CLERGY", _
"CLERIC", _
"CLERICAL", _
"CLERICS", _
"CLERKED", _
"CLERKING", _
"CLERKS", _
"CLEVERLY", _
"CLICHES", _
"CLICKED", _
"CLICKING", _
"CLICKS", _
"CLIFFS", _
"CLIMATES", _
"CLIMAX", _
"CLIMAXED", _
"CLIMAXES", _
"CLIMBER", _
"CLIMBERS", _
"CLIMES", _
"CLINCH", _
"CLINCHED", _
"CLINCHES", _
"CLINGING", _
"CLINGS", _
"CLINICS", _
"CLINKED", _
"CLINKING", _
"CLINKS", _
"CLIQUES", _
"CLITORIS", _
"CLOAKED", _
"CLOAKING", _
"CLOAKS", _
"CLOCKED", _
"CLOCKING", _
"CLOGGED", _
"CLOGGING", _
"CLOISTER", _
"CLOSETED", _
"CLOSETS", _
"CLOSURES", _
"CLOTHS", _
"CLOTTED", _
"CLOTTING", _
"CLOUDED", _
"CLOUDIER", _
"CLOUDING", _
"CLOUDY", _
"CLOUTED", _
"CLOUTING", _
"CLOUTS", _
"CLOVEN", _
"CLOVER", _
"CLOVERS", _
"CLOVES", _
"CLOWNED", _
"CLOWNING", _
"CLOWNS", _
"CLUBBED", _
"CLUBBING", _
"CLUCKED", _
"CLUCKING", _
"CLUCKS", _
"CLUELESS", _
"CLUING", _
"CLUMPED", _
"CLUMPING", _
"CLUMPS", _
"CLUMSIER", _
"CLUMSILY", _
"CLUTCH", _
"CLUTCHED", _
"CLUTCHES", _
"CLUTTER", _
"CLUTTERS", _
"COACHED", _
"COACHES", _
"COACHING", _
"COALED", _
"COALESCE", _
"COALING", _
"COARSELY", _
"COARSEN", _
"COARSENS", _
"COARSER", _
"COARSEST", _
"COASTAL", _
"COASTED", _
"COASTER", _
"COASTERS", _
"COASTING", _
"COASTS", _
"COATED", _
"COATING", _
"COAXED", _
"COAXES", _
"COAXING", _
"COBALT", _
"COBBLE", _
"COBRAS", _
"COBWEB", _
"COBWEBS", _
"COCAINE", _
"COCKED", _
"COCKEYED", _
"COCKIER", _
"COCKIEST", _
"COCKING", _
"COCKPIT", _
"COCKPITS", _
"COCKTAIL", _
"COCOAS", _
"COCONUT", _
"COCONUTS", _
"COCOON", _
"COCOONED", _
"COCOONS", _
"CODDED", _
"CODDING", _
"COERCE", _
"COERCED", _
"COERCES", _
"COERCING", _
"COERCION", _
"COEXIST", _
"COEXISTS", _
"COFFEES", _
"COFFER", _
"COFFERS", _
"COFFIN", _
"COFFINED", _
"COFFINS", _
"COGENCY", _
"COGENT", _
"COGNAC", _
"COGNACS", _
"COILED", _
"COILING", _
"COINAGE", _
"COINAGES", _
"COKING", _
"COLANDER", _
"COLDER", _
"COLDEST", _
"COLDLY", _
"COLDNESS", _
"COLLAGE", _
"COLLAGES", _
"COLLARED", _
"COLLARS", _
"COLLIDE", _
"COLLIDED", _
"COLLIDES", _
"COLLIE", _
"COLLIES", _
"COLONEL", _
"COLONELS", _
"COLONES", _
"COLONIAL", _
"COLONIES", _
"COLONS", _
"COLOSSAL", _
"COMBATED", _
"COMBATS", _
"COMBED", _
"COMBING", _
"COMEBACK", _
"COMEDIAN", _
"COMEDIES", _
"COMELIER", _
"COMELY", _
"COMETS", _
"COMFORTS", _
"COMICAL", _
"COMINGS", _
"COMMANDO", _
"COMMEND", _
"COMMENDS", _
"COMMERCE", _
"COMMONER", _
"COMMUNE", _
"COMMUNED", _
"COMMUNES", _
"COMMUTE", _
"COMMUTED", _
"COMMUTER", _
"COMMUTES", _
"COMPACTS", _
"COMPASS", _
"COMPLIED", _
"COMPLIES", _
"COMPOST", _
"COMPOSTS", _
"COMRADE", _
"COMRADES", _
"CONCAVE", _
"CONCEDED", _
"CONCEDES", _
"CONCEIT", _
"CONCEITS", _
"CONCISER", _
"CONCOCT", _
"CONCOCTS", _
"CONCORD", _
"CONCURS", _
"CONDOMS", _
"CONDONED", _
"CONDONES", _
"CONDOR", _
"CONDORS", _
"CONFER", _
"CONFERS", _
"CONFETTI", _
"CONFIDE", _
"CONFIDED", _
"CONFIDES", _
"CONFORMS", _
"CONFOUND", _
"CONGEAL", _
"CONGEALS", _
"CONGRESS", _
"CONICAL", _
"CONIFER", _
"CONIFERS", _
"CONJUGAL", _
"CONJURE", _
"CONJURED", _
"CONJURES", _
"CONNED", _
"CONNING", _
"CONNOTE", _
"CONNOTED", _
"CONNOTES", _
"CONQUER", _
"CONQUERS", _
"CONQUEST", _
"CONSERVE", _
"CONSIGN", _
"CONSIGNS", _
"CONSOLED", _
"CONSOLES", _
"CONSOMME", _
"CONSORT", _
"CONSORTS", _
"CONSPIRE", _
"CONSTRUE", _
"CONSUL", _
"CONSULAR", _
"CONSULS", _
"CONTENDS", _
"CONTESTS", _
"CONTORT", _
"CONTORTS", _
"CONTOURS", _
"CONTRITE", _
"CONVENE", _
"CONVENED", _
"CONVENES", _
"CONVENT", _
"CONVENTS", _
"CONVERGE", _
"CONVEX", _
"CONVEYED", _
"CONVEYS", _
"CONVOY", _
"CONVOYED", _
"CONVOYS", _
"CONVULSE", _
"COOING", _
"COOKBOOK", _
"COOKER", _
"COOLER", _
"COOLERS", _
"COOLEST", _
"COOLLY", _
"COOPED", _
"COOPER", _
"COOPING", _
"COPIER", _
"COPIERS", _
"COPIOUS", _
"COPPED", _
"COPPERS", _
"COPPING", _
"COPULATE", _
"CORALS", _
"CORDED", _
"CORDIAL", _
"CORDIALS", _
"CORDING", _
"CORDLESS", _
"CORDON", _
"CORDONED", _
"CORDONS", _
"CORDUROY", _
"CORING", _
"CORKED", _
"CORKING", _
"CORNEA", _
"CORNEAS", _
"CORNED", _
"CORNERED", _
"CORNET", _
"CORNETS", _
"CORNIER", _
"CORNIEST", _
"CORNING", _
"CORNMEAL", _
"CORONARY", _
"CORONER", _
"CORONERS", _
"CORPORAL", _
"CORPUS", _
"CORRAL", _
"CORRALS", _
"CORRODE", _
"CORRODED", _
"CORRODES", _
"CORSAGE", _
"CORSAGES", _
"CORSET", _
"CORSETED", _
"CORSETS", _
"CORTEX", _
"COSMETIC", _
"COSMOS", _
"COSMOSES", _
"COSTINGS", _
"COSTLIER", _
"COSTUME", _
"COSTUMED", _
"COSTUMES", _
"COTTAGE", _
"COTTAGES", _
"COTTONED", _
"COTTONS", _
"COUCHED", _
"COUCHES", _
"COUCHING", _
"COUGAR", _
"COUGARS", _
"COUGHED", _
"COUGHING", _
"COUGHS", _
"COUNTERS", _
"COUNTESS", _
"COUNTIES", _
"COUPON", _
"COUPONS", _
"COURIERS", _
"COURSED", _
"COURSER", _
"COURSING", _
"COURTED", _
"COURTING", _
"COUSINS", _
"COVENANT", _
"COVERT", _
"COVERTLY", _
"COVERTS", _
"COVETED", _
"COVETING", _
"COVETOUS", _
"COVETS", _
"COWARD", _
"COWARDLY", _
"COWARDS", _
"COWBOY", _
"COWBOYS", _
"COWERED", _
"COWERING", _
"COWERS", _
"COWGIRL", _
"COWGIRLS", _
"COWHIDE", _
"COWHIDES", _
"COWING", _
"COYEST", _
"COYOTE", _
"COYOTES", _
"CRABBED", _
"CRABBIER", _
"CRABBING", _
"CRABBY", _
"CRACKER", _
"CRACKERS", _
"CRACKLE", _
"CRACKLED", _
"CRACKLES", _
"CRACKPOT", _
"CRADLE", _
"CRADLED", _
"CRADLES", _
"CRADLING", _
"CRAFTED", _
"CRAFTIER", _
"CRAFTILY", _
"CRAFTING", _
"CRAFTS", _
"CRAFTY", _
"CRAGGIER", _
"CRAGGY", _
"CRAMMED", _
"CRAMMING", _
"CRANED", _
"CRANES", _
"CRANING", _
"CRANIUM", _
"CRANIUMS", _
"CRANKED", _
"CRANKIER", _
"CRANKING", _
"CRANKS", _
"CRANKY", _
"CRASSER", _
"CRASSEST", _
"CRATED", _
"CRATER", _
"CRATERED", _
"CRATERS", _
"CRATES", _
"CRATING", _
"CRAVED", _
"CRAVES", _
"CRAVING", _
"CRAVINGS", _
"CRAYFISH", _
"CRAYON", _
"CRAYONED", _
"CRAYONS", _
"CRAZED", _
"CRAZES", _
"CRAZIER", _
"CRAZIES", _
"CRAZIEST", _
"CRAZILY", _
"CRAZING", _
"CREAKED", _
"CREAKIER", _
"CREAKING", _
"CREAKS", _
"CREAKY", _
"CREAMED", _
"CREAMIER", _
"CREAMING", _
"CREAMS", _
"CREAMY", _
"CREASE", _
"CREASED", _
"CREASES", _
"CREASING", _
"CREATORS", _
"CREDENCE", _
"CREDITED", _
"CREDITOR", _
"CREEDS", _
"CREEKS", _
"CREEPIER", _
"CREEPING", _
"CREEPS", _
"CREEPY", _
"CREMATE", _
"CREMATED", _
"CREMATES", _
"CREPES", _
"CRESCENT", _
"CRESTED", _
"CRESTING", _
"CRESTS", _
"CRETIN", _
"CRETINS", _
"CREVASSE", _
"CREVICE", _
"CREVICES", _
"CREWED", _
"CREWING", _
"CRIBBED", _
"CRIBBING", _
"CRICKETS", _
"CRIMSON", _
"CRIMSONS", _
"CRINGE", _
"CRINGED", _
"CRINGES", _
"CRINGING", _
"CRINKLE", _
"CRINKLED", _
"CRINKLES", _
"CRIPPLE", _
"CRIPPLED", _
"CRIPPLES", _
"CRISES", _
"CRISPED", _
"CRISPER", _
"CRISPEST", _
"CRISPING", _
"CRISPLY", _
"CRISPY", _
"CRITIQUE", _
"CROAKED", _
"CROAKING", _
"CROAKS", _
"CROCHET", _
"CROCHETS", _
"CROCKERY", _
"CROCKS", _
"CROCUS", _
"CROCUSES", _
"CROFTS", _
"CRONIES", _
"CROOKED", _
"CROOKING", _
"CROOKS", _
"CROONED", _
"CROONING", _
"CROONS", _
"CROPPED", _
"CROPPING", _
"CROQUET", _
"CROSSBOW", _
"CROSSER", _
"CROSSEST", _
"CROTCH", _
"CROTCHES", _
"CROUCH", _
"CROUCHED", _
"CROUCHES", _
"CROWBAR", _
"CROWBARS", _
"CROWED", _
"CROWING", _
"CROWNED", _
"CROWNING", _
"CROWNS", _
"CRUCIFIX", _
"CRUCIFY", _
"CRUDELY", _
"CRUDER", _
"CRUDEST", _
"CRUDITY", _
"CRUELLY", _
"CRUISER", _
"CRUISERS", _
"CRUMBED", _
"CRUMBING", _
"CRUMBLE", _
"CRUMBLED", _
"CRUMBLES", _
"CRUMBLY", _
"CRUMBS", _
"CRUMMIER", _
"CRUMMY", _
"CRUMPLE", _
"CRUMPLED", _
"CRUMPLES", _
"CRUNCHY", _
"CRUSADE", _
"CRUSADED", _
"CRUSADER", _
"CRUSADES", _
"CRUSTED", _
"CRUSTIER", _
"CRUSTING", _
"CRUSTS", _
"CRUSTY", _
"CRUTCH", _
"CRUTCHES", _
"CRUXES", _
"CRYBABY", _
"CRYPTS", _
"CUBICLE", _
"CUBICLES", _
"CUBING", _
"CUCKOOS", _
"CUCUMBER", _
"CUDDLE", _
"CUDDLED", _
"CUDDLES", _
"CUDDLING", _
"CUFFED", _
"CUFFING", _
"CUISINE", _
"CUISINES", _
"CULINARY", _
"CULLED", _
"CULLING", _
"CULPABLE", _
"CULPRITS", _
"CULTURED", _
"CUPFUL", _
"CUPFULS", _
"CUPPED", _
"CUPPING", _
"CURABLE", _
"CURATOR", _
"CURATORS", _
"CURBED", _
"CURBING", _
"CURDLE", _
"CURDLED", _
"CURDLES", _
"CURDLING", _
"CURFEW", _
"CURFEWS", _
"CURIOS", _
"CURLED", _
"CURLING", _
"CURRANT", _
"CURRANTS", _
"CURRENTS", _
"CURRIED", _
"CURRIES", _
"CURRYING", _
"CURSED", _
"CURSES", _
"CURSING", _
"CURSORY", _
"CURTAIL", _
"CURTAILS", _
"CURTER", _
"CURTEST", _
"CURTSIED", _
"CURTSIES", _
"CURTSY", _
"CURVED", _
"CURVING", _
"CUSHION", _
"CUSHIONS", _
"CUSTARDS", _
"CUSTODY", _
"CUTBACK", _
"CUTBACKS", _
"CUTEST", _
"CUTICLE", _
"CUTICLES", _
"CUTLERY", _
"CUTLET", _
"CUTLETS", _
"CUTTER", _
"CUTTERS", _
"CUTTINGS", _
"CYANIDE", _
"CYCLIC", _
"CYCLONE", _
"CYCLONES", _
"CYMBAL", _
"CYMBALS", _
"CYNICISM", _
"CYNICS", _
"CYPRESS", _
"DABBED", _
"DABBING", _
"DABBLE", _
"DABBLED", _
"DABBLES", _
"DABBLING", _
"DADDIES", _
"DAEMON", _
"DAFFODIL", _
"DAGGER", _
"DAGGERS", _
"DAILIES", _
"DAINTIER", _
"DAINTIES", _
"DAINTILY", _
"DAINTY", _
"DAIRIES", _
"DAISES", _
"DAISIES", _
"DALLIED", _
"DALLIES", _
"DALLYING", _
"DAMMED", _
"DAMMING", _
"DAMPED", _
"DAMPEN", _
"DAMPENED", _
"DAMPENS", _
"DAMPER", _
"DAMPEST", _
"DAMPING", _
"DAMPNESS", _
"DAMSEL", _
"DAMSELS", _
"DANCER", _
"DANCERS", _
"DANDIER", _
"DANDIES", _
"DANDIEST", _
"DANDRUFF", _
"DANGLE", _
"DANGLED", _
"DANGLES", _
"DANGLING", _
"DANKER", _
"DANKEST", _
"DAPPER", _
"DAPPERER", _
"DARKEN", _
"DARKENED", _
"DARKENS", _
"DARKER", _
"DARKEST", _
"DARKLY", _
"DARLINGS", _
"DARNED", _
"DARNING", _
"DARTED", _
"DARTING", _
"DAUBED", _
"DAUBING", _
"DAUNTED", _
"DAUNTING", _
"DAUNTS", _
"DAWDLE", _
"DAWDLED", _
"DAWDLES", _
"DAWDLING", _
"DAWNED", _
"DAWNING", _
"DAYBREAK", _
"DAYDREAM", _
"DAZING", _
"DAZZLE", _
"DAZZLED", _
"DAZZLES", _
"DAZZLING", _
"DEACON", _
"DEACONS", _
"DEADEN", _
"DEADENED", _
"DEADENS", _
"DEADER", _
"DEADEST", _
"DEADLIER", _
"DEADLOCK", _
"DEAFER", _
"DEAFEST", _
"DEAFNESS", _
"DEALINGS", _
"DEARER", _
"DEAREST", _
"DEARLY", _
"DEARTH", _
"DEARTHS", _
"DEATHBED", _
"DEAVES", _
"DEBASE", _
"DEBASED", _
"DEBASES", _
"DEBASING", _
"DEBILITY", _
"DEBITED", _
"DEBITING", _
"DEBITS", _
"DEBONAIR", _
"DEBRIEF", _
"DEBRIEFS", _
"DEBRIS", _
"DEBTOR", _
"DEBTORS", _
"DEBUNK", _
"DEBUNKED", _
"DEBUNKS", _
"DEBUTED", _
"DEBUTING", _
"DEBUTS", _
"DECADENT", _
"DECANTER", _
"DECAYED", _
"DECAYING", _
"DECAYS", _
"DECEASE", _
"DECEASED", _
"DECEASES", _
"DECEIT", _
"DECEITS", _
"DECEIVE", _
"DECEIVED", _
"DECEIVES", _
"DECENCY", _
"DECENTLY", _
"DECIBEL", _
"DECIBELS", _
"DECIMALS", _
"DECIMATE", _
"DECIPHER", _
"DECISIVE", _
"DECKED", _
"DECKING", _
"DECODER", _
"DECORATE", _
"DECOROUS", _
"DECORUM", _
"DECOYED", _
"DECOYING", _
"DECOYS", _
"DECREE", _
"DECREED", _
"DECREES", _
"DECREPIT", _
"DECRIED", _
"DECRIES", _
"DECRYING", _
"DEDUCT", _
"DEDUCTED", _
"DEDUCTS", _
"DEEDED", _
"DEEDING", _
"DEEPEN", _
"DEEPENED", _
"DEEPENS", _
"DEFACE", _
"DEFACED", _
"DEFACES", _
"DEFACING", _
"DEFAME", _
"DEFAMED", _
"DEFAMES", _
"DEFAMING", _
"DEFECATE", _
"DEFECTED", _
"DEFENDER", _
"DEFERRED", _
"DEFERS", _
"DEFIANCE", _
"DEFIANT", _
"DEFICIT", _
"DEFICITS", _
"DEFIED", _
"DEFIES", _
"DEFILE", _
"DEFILED", _
"DEFILES", _
"DEFILING", _
"DEFLATE", _
"DEFLATED", _
"DEFLATES", _
"DEFLECT", _
"DEFLECTS", _
"DEFORM", _
"DEFORMED", _
"DEFORMS", _
"DEFRAUD", _
"DEFRAUDS", _
"DEFROST", _
"DEFROSTS", _
"DEFTER", _
"DEFTEST", _
"DEFTLY", _
"DEFUNCT", _
"DEFYING", _
"DEIFIED", _
"DEIFIES", _
"DEIFYING", _
"DEIGNED", _
"DEIGNING", _
"DEIGNS", _
"DEITIES", _
"DEJECT", _
"DEJECTED", _
"DEJECTS", _
"DELEGATE", _
"DELICACY", _
"DELIMIT", _
"DELIMITS", _
"DELIRIUM", _
"DELTAS", _
"DELUDE", _
"DELUDED", _
"DELUDES", _
"DELUDING", _
"DELUGE", _
"DELUGED", _
"DELUGES", _
"DELUGING", _
"DELUXE", _
"DELVED", _
"DELVES", _
"DELVING", _
"DEMEAN", _
"DEMEANED", _
"DEMEANS", _
"DEMENTIA", _
"DEMERIT", _
"DEMERITS", _
"DEMISED", _
"DEMISES", _
"DEMISING", _
"DEMOCRAT", _
"DEMONS", _
"DEMOTE", _
"DEMOTED", _
"DEMOTES", _
"DEMOTING", _
"DEMOTION", _
"DEMOUNT", _
"DEMURE", _
"DEMURELY", _
"DEMURER", _
"DEMUREST", _
"DENIAL", _
"DENIALS", _
"DENIMS", _
"DENOTED", _
"DENOTING", _
"DENOUNCE", _
"DENSELY", _
"DENSER", _
"DENSEST", _
"DENTAL", _
"DENTED", _
"DENTING", _
"DENTISTS", _
"DEPART", _
"DEPARTED", _
"DEPARTS", _
"DEPICT", _
"DEPICTED", _
"DEPICTS", _
"DEPLETE", _
"DEPLETED", _
"DEPLETES", _
"DEPLORE", _
"DEPLORED", _
"DEPLORES", _
"DEPORT", _
"DEPORTED", _
"DEPORTS", _
"DEPOSE", _
"DEPOSED", _
"DEPOSES", _
"DEPOSING", _
"DEPOSITS", _
"DEPOTS", _
"DEPRAVE", _
"DEPRAVED", _
"DEPRAVES", _
"DEPUTIES", _
"DERAIL", _
"DERAILED", _
"DERAILS", _
"DERELICT", _
"DERIDE", _
"DERIDED", _
"DERIDES", _
"DERIDING", _
"DERISION", _
"DERRICK", _
"DERRICKS", _
"DESCENT", _
"DESCENTS", _
"DESERTER", _
"DESIROUS", _
"DESIST", _
"DESISTED", _
"DESISTS", _
"DESOLATE", _
"DESPAIRS", _
"DESPISED", _
"DESPISES", _
"DESPOT", _
"DESPOTIC", _
"DESPOTS", _
"DESSERT", _
"DESSERTS", _
"DESTINY", _
"DETAIN", _
"DETAINED", _
"DETAINS", _
"DETERRED", _
"DETERS", _
"DETEST", _
"DETESTED", _
"DETESTS", _
"DETHRONE", _
"DETONATE", _
"DETOUR", _
"DETOURED", _
"DETOURS", _
"DETRACTS", _
"DEVALUE", _
"DEVIANT", _
"DEVIATE", _
"DEVIATED", _
"DEVIATES", _
"DEVILS", _
"DEVOLVE", _
"DEVOLVED", _
"DEVOLVES", _
"DEVOTEE", _
"DEVOTEES", _
"DEVOTION", _
"DEVOUR", _
"DEVOURED", _
"DEVOURS", _
"DEVOUT", _
"DEVOUTER", _
"DEVOUTLY", _
"DIABETES", _
"DIABETIC", _
"DIAGNOSE", _
"DIALOG", _
"DIAMOND", _
"DIAMONDS", _
"DIAPER", _
"DIAPERED", _
"DIAPERS", _
"DIARIES", _
"DIATRIBE", _
"DICING", _
"DICTATED", _
"DICTATES", _
"DICTION", _
"DIESELED", _
"DIESELS", _
"DIETARY", _
"DIETED", _
"DIETING", _
"DIFFUSE", _
"DIFFUSED", _
"DIFFUSES", _
"DIGESTED", _
"DIGESTS", _
"DIGNIFY", _
"DIGRESS", _
"DIKING", _
"DILATE", _
"DILATED", _
"DILATES", _
"DILATING", _
"DILATION", _
"DILEMMAS", _
"DILIGENT", _
"DILUTE", _
"DILUTED", _
"DILUTES", _
"DILUTING", _
"DILUTION", _
"DIMINISH", _
"DIMMED", _
"DIMMER", _
"DIMMEST", _
"DIMMING", _
"DISEASED", _
"DISGRACE", _
"DISHED", _
"DISHING", _
"DISJOINT", _
"DISLODGE", _
"DISLOYAL", _
"DISMALLY", _
"DISMAY", _
"DISMAYED", _
"DISMAYS", _
"DISMOUNT", _
"DISOBEY", _
"DISOBEYS", _
"DISOWN", _
"DISOWNED", _
"DISOWNS", _
"DISPATCH", _
"DISPEL", _
"DISPELS", _
"DISPENSE", _
"DISPERSE", _
"DISPLACE", _
"DISPROVE", _
"DISPUTED", _
"DISPUTES", _
"DISQUIET", _
"DISRUPTS", _
"DISSECT", _
"DISSECTS", _
"DISSENT", _
"DISSENTS", _
"DOODLED", _
"DOODLES", _
"DOODLING", _
"DOORMAN", _
"DOORMEN", _
"DOORSTEP", _
"DOORWAY", _
"DOORWAYS", _
"DOPIER", _
"DOPIEST", _
"DOPING", _
"DORMANT", _
"DORSAL", _
"DOSING", _
"DOTING", _
"DOUBLY", _
"DOUBTED", _
"DOUBTING", _
"DOUGHNUT", _
"DOURER", _
"DOUREST", _
"DOUSED", _
"DOUSES", _
"DOUSING", _
"DOWDIER", _
"DOWDIES", _
"DOWDIEST", _
"DOWNCAST", _
"DOWNED", _
"DOWNFALL", _
"DOWNIER", _
"DOWNIEST", _
"DOWNING", _
"DOWNPOUR", _
"DOWNTOWN", _
"DOWNWARD", _
"DUPLEX", _
"DUPLEXES", _
"DURABLE", _
"DURESS", _
"DUSKIER", _
"DUSKIEST", _
"DUSTED", _
"DUSTIER", _
"DUSTIEST", _
"DUSTING", _
"DUSTMEN", _
"DUSTPAN", _
"DUSTPANS", _
"DUTIFUL", _
"DWARFED", _
"DWARFING", _
"DWARFS", _
"DWELLER", _
"DWELLERS", _
"DWELLING", _
"DWELLS", _
"DWINDLE", _
"DWINDLED", _
"DWINDLES", _
"DYEING", _
"DYNAMITE", _
"DYNAMO", _
"DYNAMOS", _
"DYNASTY", _
"DYSLEXIA", _
"EAGERER", _
"EAGEREST", _
"EAGLES", _
"EARACHE", _
"EARACHES", _
"EARDRUM", _
"EARDRUMS", _
"EARMARK", _
"EARMARKS", _
"EARNER", _
"EARNERS", _
"EARNEST", _
"EARNESTS", _
"EARNINGS", _
"EARRING", _
"EARRINGS", _
"EARSHOT", _
"JAYWALKS", _
"JAZZED", _
"JAZZES", _
"JAZZING", _
"JEALOUSY", _
"JEERED", _
"KIMONOS", _
"KINDER", _
"KINDEST", _
"KINDLE", _
"KINDLED", _
"KINDLES", _
"KINDLIER", _
"LEERIEST", _
"LEERING", _
"LEEWAY", _
"LEFTER", _
"LEFTEST", _
"LEFTMOST", _
"LEGACIES", _
"LEGACY", _
"LEGALITY", _
"LEGALS", _
"LEGENDS", _
"LEGGED", _
"LEGGING", _
"LEGGINGS", _
"LEGIBLY", _
"MALTED", _
"ZEROING", _
"ZIGZAG", _
"ZIGZAGS", _
"ZILLION", _
"ZILLIONS", _
"ZINCKED", _
"ZINCKING", _
"ZIPPED", _
"ZIPPER", _
"ZIPPERED", _
"ZIPPERS", _
"ZIPPING", _
"ZODIAC", _
"ZODIACS", _
"ZOMBIE", _
"ZOMBIES", _
"ZONING", _
"ZOOLOGY", _
"ZOOMED", _
"ZOOMING", _
"ZUCCHINI"}

    '*[null pixel]Numbers[repeat count], #[text]Numbers[repeat count], &[row reference]number[referenced row index]
    'First row [font height, chars...]
    'Following rows [char width, pixel maps...]
    Private FontMap() As Array = { _
        Split("13,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,0,1,2,3,4,5,6,7,8,9", ","), _
        Split("14,*5#4*5,*4#6*4,&2,&2,*3#3*2#3*3,&5,*2#4*2#4*2,*2#3*4#3*2,*2#10*2,*1#12*1,*1#3*6#3*1,&11,#3*8#3", ","), _
        Split("11,#8*3,#10*1,#3*4#3*1,&3,&3,&1,&2,#3*4#4,#3*5#3,&9,&8,&2,#9*2", ","), _
        Split("11,*4#6*1,*2#9,*1#4*4#2,*1#3*6#1,#3*8,&5,&5,&5,&5,&4,&3,&2,&1", ","), _
        Split("12,#8*4,#10*2,#3*4#4*1,#3*5#3*1,#3*6#3,&5,&5,&5,&5,&4,&3,&2,&1", ","), _
        Split("9,#9,&1,#3*6,&3,&3,#8*1,&6,&3,&3,&3,&3,&1,&1", ","), _
        Split("9,#9,&1,#3*6,&3,&3,&1,&1,&3,&3,&3,&3,&3,&3", ","), _
        Split("13,*4#7,*2#11,*1#4*5#3,*1#3*8#1,#3,#3,#3*4#6,&7,#3*7#3,*1#3*6#3,*1#5*4#3,&2,&1", ","), _
        Split("11,#3*5#3,&1,&1,&1,&1,#11,&6,&1,&1,&1,&1,&1,&1", ","), _
        Split("7,#7,#7,*2#3,&3,&3,&3,&3,&3,&3,&3,&3,&1,&1", ","), _
        Split("8,*2#6,&1,*5#3,&3,&3,&3,&3,&3,&3,&3,*4#4,#7,#6", ","), _
        Split("12,#3*5#4,#3*4#4,#3*3#4,#3*2#4,#3*2#3,#3*1#3,#7,#8,&5,#3*3#3,#3*4#3,#3*5#3,&1", ","), _
        Split("9,#3,#3,#3,#3,#3,#3,#3,#3,#3,#3,#3,#9,#9", ","), _
        Split("13,#3*7#3,#4*5#4,&2,#5*3#5,&4,#6*1#6,#3*1#2*1#2*1#3,#3*1#5*1#3,#3*2#3*2#3,&9,#3*7#3,&11,&11", ","), _
        Split("11,#4*4#3,#5*3#3,&2,#6*2#3,&4,#3*1#3*1#3,&6,#3*2#6,&8,#3*3#5,&10,#3*4#4,#3*5#3", ","), _
        Split("13,*4#5,*2#9,*1#4*3#4,*1#3*5#3,#3*7#3,&5,&5,&5,&5,&4,&3,&2,&1", ","), _
        Split("10,#8,#9,#3*3#4,#3*4#3,&4,&4,&3,&2,#7,#3,#3,#3,#3", ","), _
        Split("13,*3#6,*2#8,*1#3*4#3,*1#2*6#2,#3*7#2,#2*8#2,&6,#2*5#1*2#2,#3*3#3*1#2,*1#2*4#4,*1#3*4#3,*2#10,*3#6*1#1", ","), _
        Split("12,#8,#9,#3*4#3,&3,&3,#3*3#4,&2,&1,#3*2#4,#3*3#3,&3,#3*4#4,#3*5#4", ","), _
        Split("11,*3#6,*1#9,#4*4#2,#3*6#1,#4,#8,&2,*3#8,*7#4,#1*7#3,#3*4#4,#10,*1#7", ","), _
        Split("11,#11,&1,*4#3,&3,&3,&3,&3,&3,&3,&3,&3,&3,&3", ","), _
        Split("11,#3*5#3,&1,&1,&1,&1,&1,&1,&1,&1,&1,#4*3#4,*1#9,*3#5", ","), _
        Split("14,#3*8#3,*1#3*6#3,&2,*1#3*5#4,*2#3*4#3,&5,*3#3*2#3,&7,&7,*4#6,&10,&10,*5#4", ","), _
        Split("17,#3*4#3*4#3,&1,#3*3#5*3#3,*1#3*2#2*1#2*2#3,&4,*1#3*1#3*1#3*1#3,&6,*1#3*1#2*3#2*1#3,&8,*2#5*3#5,&10,*2#4*5#4,&12", ","), _
        Split("14,#4*6#4,*1#4*4#4,*2#4*2#4,*3#3*2#3,*3#8,*4#6,*5#4,&6,&5,&4,&3,&2,&1", ","), _
        Split("13,#4*5#4,*1#3*5#3,*2#3*3#3,*2#4*1#4,*3#3*1#3,*3#7,*4#5,*5#3,&8,&8,&8,&8,&8", ","), _
        Split("10,#10,&1,*6#4,*5#4,*5#3,*4#3,*3#4,*3#3,*2#3,*1#4,#4,&1,&1", ","), _
        Split("10,*3#4,*1#8,*1#3*3#2,#2*5#3,#2*4#4,#2*3#2*1#2,#2*2#2*2#2,#2*1#2*3#2,#4*4#2,#3*5#2,*1#2*3#3,*1#8,*3#4", ","), _
        Split("9,*3#3*3,&1,#6*3,&3,*3#3*3,&5,&5,&5,&5,&5,&5,#9,&12", ","), _
        Split("10,*1#6*3,#8*2,#2*3#4*1,#1*5#3*1,*6#3*1,&5,*5#3*2,*4#4*2,*3#4*3,*2#4*4,*1#4*5,#10,&12", ","), _
        Split("11,*1#8*2,#10*1,#3*5#3,#1*7#3,*7#3*1,*3#6*2,*3#7*1,*7#4,*8#3,&4,#3*4#4,&2,*1#7*3", ","), _
        Split("12,*6#4*2,*5#5*2,&2,*4#2*1#3*2,*3#3*1#3*2,*2#3*2#3*2,*1#3*3#3*2,#3*4#3*2,#12,&9,*7#3*2,&11,&11", ","), _
        Split("11,*1#10,&1,*1#3*7,&3,*1#8*2,*1#9*1,*7#4,*8#3,&8,#1*7#3,#3*4#3*1,#10*1,*1#7*3", ","), _
        Split("11,*4#6*1,*2#8*1,*1#4*6,*1#3*7,#3*1#5*2,#10*1,#3*4#4,#3*5#3,&8,&8,*1#3*3#3*1,*1#9*1,*3#5*3", ","), _
        Split("11,#11,&1,*7#4,*7#3*1,*6#4*1,*6#3*2,*5#3*3,*4#4*3,*4#3*4,*3#4*4,*3#3*5,*2#3*6,*1#4*6", ","), _
        Split("11,*2#7*2,*1#9*1,#3*4#4,#3*5#3,#4*3#3*1,*1#8*2,&1,*1#3*1#5*1,&4,&4,#4*3#4,&2,*2#6*3", ","), _
        Split("11,*3#5*3,*1#9*1,*1#3*3#3*1,#3*5#3,&4,&4,#4*4#3,*1#10,*2#5*1#3,*7#3*1,*6#4*1,*1#8*2,*1#6*4", ",") _
    } 'Previous row must end with _

    '#Begin ColorMap
    Const BmpColorMap = "f7fcfc000c85810085241000"

    Private ColorMap() As Array = { _
    Split("00,01,02", ",") _
    } 'End ColorMap


    '#Auto calculated variables
    Dim ImageWidth As Integer
    Dim ImageHeight As Integer
    Dim arrTextWidth() As Integer
    Dim TextHeight As Integer
    Dim LeftMargin As Integer
    Dim arrTopMargin() As Integer
    Dim CursorPos As Integer
    Dim BmpEndLine As String
    Dim BColor, TColor, NColor As String
    Dim i, j, k, x, y As Integer

    '#Editable consts and variables
    Dim Bitmap(25, 130) As String '[Height,Width]
    Dim CodeLength = 6 'Secure code length (Max:8)
    Const CodeType = 1 '0[Random numbers], 1[Random chars and numbers], 2[Wordlist]
    Const CharTracking = 2 'Set the tracking between two characters
    Const RndTopMargin = True 'Randomize top margin every character
    Const NoiseEffect = 2 '0[none], 1[sketch], 2[random foreground lines], 3[Random lines of background color over text (Recommed maximum NoiseLine=4)]
    Const NoiseLine = 6 'Low values make easy OCR, high values decrease readability
    Const MinLineLength = 7 'Minimum noise line length
    Const SessionName = "ASPCAPTCHA" 'Where store your secure code

    '#Global variables
    Dim Ctx As HttpContext
    Dim secureCode As String
    Dim mRnd As Random = New Random()


    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Ctx = Context
        If CodeType < 2 Then
            secureCode = CreateGUID(CodeLength)
        Else
            secureCode = RandomWord()
            CodeLength = secureCode.Length
        End If
        Context.Session(SessionName) = secureCode
        PrepareBitmap(secureCode)
        If NoiseEffect > 0 Then
            AddNoise()
        End If
        SendBitmap()
    End Sub

    'Public Sub ProcessRequest(ByVal context As HttpContext) Implements IHttpHandler.ProcessRequest

    'End Sub

    'Public ReadOnly Property IsReusable() As Boolean Implements IHttpHandler.IsReusable
    '    Get
    '        Return False
    '    End Get
    'End Property

    Private Function CreateGUID(ByVal valLength As Integer) As String
        Dim strValid As String
        If CodeType = 1 Then
            strValid = "A0B1C2D3E4F5G6H7I8J9K8L7M6N5O4P3Q2R1S0T1U2V3W4X5Y6Z7"
        Else
            strValid = "0516273849"
        End If
        Dim tmpGUID As String = vbNullString
        Dim tmpChr As String = vbNullString
        For cGUID As Integer = 1 To valLength
            Do
                tmpChr = Mid(strValid, RndInterval(1, Len(strValid)), 1)
            Loop While CStr(tmpChr) = CStr(Right(tmpGUID, 1))
            tmpGUID = tmpGUID & tmpChr
        Next
        'CreateGUID = tmpGUID
        Return tmpGUID
    End Function

    Function RandomWord() As String
        Return words(RndInterval(0, UBound(words)))
    End Function

    Function RndInterval(ByVal valMin As Integer, ByVal valMax As Integer) As Integer
        RndInterval = mRnd.Next(valMin, (valMax + 1))
    End Function

    Function GetCharMap(ByVal valChr As String) As Array
        Dim i, j As Integer
        j = 0
        For i = 1 To UBound(FontMap(0))
            If CStr(FontMap(0)(i)) = CStr(valChr) Then
                j = i
                Exit For
            End If
        Next

        If j > 0 Then
            GetCharMap = FontMap(j)
        Else
            GetCharMap = New Array() {}
        End If
    End Function

    Sub WriteCanvas(ByVal valChr As String, ByVal valTopMargin As Integer)
        Dim i, j, k, curPos As Integer
        Dim tmpChr, strPixMap, pixRepeat As String
        Dim arrChrMap() As String
        Dim drawPixel As Boolean

        'find char map
        arrChrMap = GetCharMap(valChr)
        If UBound(arrChrMap) < 1 Then
            Exit Sub
        End If

        'write char
        For i = 1 To UBound(arrChrMap)
            'get pixel map active line
            strPixMap = arrChrMap(i)
            If Left(strPixMap, 1) = "&" Then
                j = Mid(strPixMap, 2)
                If (IsNumeric(j) = True) Then
                    strPixMap = arrChrMap(CInt(j))
                Else
                    strPixMap = vbNullString
                End If
            End If
            strPixMap = Trim(strPixMap)

            'drawing pixel
            curPos = CursorPos
            drawPixel = False
            pixRepeat = vbNullString
            For j = 1 To Len(strPixMap)
                tmpChr = Mid(strPixMap, j, 1)
                If (IsNumeric(tmpChr) = True) And (j < Len(strPixMap)) Then
                    pixRepeat = pixRepeat & tmpChr
                Else
                    'end pixel map?
                    If IsNumeric(tmpChr) = True Then
                        pixRepeat = pixRepeat & tmpChr
                    End If

                    'draw pixel
                    If (drawPixel = True) And (IsNumeric(pixRepeat) = True) Then
                        For k = 1 To CInt(pixRepeat)
                            curPos = curPos + 1
                            Bitmap((valTopMargin + i), curPos) = TColor
                        Next
                    ElseIf IsNumeric(pixRepeat) = True Then
                        curPos = curPos + CInt(pixRepeat)
                    End If

                    'what is new command?
                    If tmpChr = "#" Then
                        drawPixel = True
                    Else
                        drawPixel = False
                    End If
                    pixRepeat = vbNullString
                End If
            Next
        Next
    End Sub

    Sub PrepareBitmap(ByVal valSecureCode As String)
        Dim i, j As Integer
        'image dimensions
        ImageWidth = UBound(Bitmap, 2)
        ImageHeight = UBound(Bitmap, 1)

        'char and text width
        ReDim arrTextWidth(CodeLength)
        arrTextWidth(0) = 0
        For i = 1 To CodeLength
            arrTextWidth(i) = CInt(GetCharMap(Mid(secureCode, i, 1))(0))
            arrTextWidth(0) = arrTextWidth(0) + arrTextWidth(i)
        Next
        arrTextWidth(0) = arrTextWidth(0) + ((CodeLength - 1) * CharTracking)

        'text height
        TextHeight = CInt(FontMap(0)(0))

        'left margin
        LeftMargin = Math.Round((ImageWidth - arrTextWidth(0)) / 2)

        'top margin
        ReDim arrTopMargin(CodeLength)
        arrTopMargin(0) = Math.Round((ImageHeight - TextHeight) / 2)
        If RndTopMargin = True Then
            For i = 1 To CodeLength
                arrTopMargin(i) = RndInterval(Math.Round(arrTopMargin(0) / 2), (arrTopMargin(0) + Math.Round(arrTopMargin(0) / 2)))
            Next
        Else
            For i = 1 To CodeLength
                arrTopMargin(i) = arrTopMargin(0)
            Next
        End If

        'color selection
        i = RndInterval(0, UBound(ColorMap))
        BColor = ColorMap(i)(0)
        NColor = ColorMap(i)(1)
        TColor = ColorMap(i)(2)

        'write text
        For i = 1 To CodeLength
            'calculate cursor pos
            CursorPos = 0
            For j = (i - 1) To 1 Step -1
                CursorPos = CursorPos + arrTextWidth(j) + CharTracking
            Next
            CursorPos = LeftMargin + CursorPos

            'write active char
            WriteCanvas(Mid(secureCode, i, 1), arrTopMargin(i))
        Next
    End Sub

    Sub DrawLine(ByVal x0 As Integer, ByVal y0 As Integer, ByVal x1 As Integer, ByVal y1 As Integer, ByVal valClr As String)
        'Reference from Donald Hearn and M. Pauline Baker, Computer Graphics C Version
        Dim m, b, dx, dy As Double
        Dim clrNoise As String

        If (NoiseEffect = 3) And (Bitmap(y0, x0) = TColor) Then
            clrNoise = vbNullString
        Else
            clrNoise = valClr
        End If
        Bitmap(y0, x0) = clrNoise

        dx = x1 - x0
        dy = y1 - y0
        If Math.Abs(dx) > Math.Abs(dy) Then
            m = (dy / dx)
            b = y0 - (m * x0)

            If dx < 0 Then
                dx = -1
            Else
                dx = 1
            End If

            Do While x0 <> x1
                x0 = x0 + dx

                If (NoiseEffect = 3) And (Bitmap(Math.Round((m * x0) + b), x0) = TColor) Then
                    clrNoise = vbNullString
                Else
                    clrNoise = valClr
                End If
                Bitmap(Math.Round((m * x0) + b), x0) = clrNoise
            Loop
        ElseIf dy <> 0 Then
            m = (dx / dy)
            b = x0 - (m * y0)

            If dy < 0 Then
                dy = -1
            Else
                dy = 1
            End If

            Do While y0 <> y1
                y0 = y0 + dy

                If (NoiseEffect = 3) And (Bitmap(y0, Math.Round((m * y0) + b)) = TColor) Then
                    clrNoise = vbNullString
                Else
                    clrNoise = valClr
                End If
                Bitmap(y0, Math.Round((m * y0) + b)) = clrNoise
            Loop
        End If
    End Sub

    Sub AddNoise()
        Dim median, i, j, x0, y0, x1, y1, dx, dy, dxy As Integer
        Dim clrNoise As String

        If NoiseEffect = 1 Then
            clrNoise = vbNullString
        Else
            clrNoise = NColor
        End If

        For i = 1 To NoiseLine
            x0 = RndInterval(1, ImageWidth)
            y0 = RndInterval(1, ImageHeight)
            x1 = RndInterval(1, ImageWidth)
            y1 = RndInterval(1, ImageHeight)

            'Check minimum line length
            dx = Math.Abs(x1 - x0)
            dy = Math.Abs(y1 - y0)
            median = Math.Round(Math.Sqrt((dx * dx) + (dy * dy)) / 2)
            If median < MinLineLength Then
                dxy = MinLineLength - median

                If x1 < x0 Then
                    dx = -1
                Else
                    dx = 1
                End If

                If y1 < y0 Then
                    dy = -1
                Else
                    dy = 1
                End If

                For j = 1 To dxy
                    If ((x1 + dx) < 1) Or ((x1 + dx) > ImageWidth) Or ((y1 + dy) < 1) Or ((y1 + dy) > ImageHeight) Then
                        Exit For
                    End If
                    x1 = x1 + dx
                    y1 = y1 + dy
                Next
            End If

            'Draw noise line
            DrawLine(x0, y0, x1, y1, clrNoise)
        Next
    End Sub

    Function FormatHex(ByVal valHex As String, ByVal fixByte As Integer, ByVal fixDrctn As Integer, ByVal valReverse As Boolean) As String
        fixByte = fixByte * 2
        Dim tmpLen As Integer = Len(valHex)
        If fixByte > tmpLen Then

            Dim tmpFixHex As String = New String("0", (fixByte - tmpLen))
            If fixDrctn = 1 Then
                valHex = valHex & tmpFixHex
            Else
                valHex = tmpFixHex & valHex
            End If
        End If

        If valReverse = True Then
            Dim tmpHex As String = vbNullString
            For cFrmtHex As Integer = 1 To Len(valHex) Step 2
                tmpHex = Mid(valHex, cFrmtHex, 2) & tmpHex
            Next
            FormatHex = tmpHex
        Else
            FormatHex = CStr(valHex)
        End If
    End Function

    Sub SendHex(ByVal valHex As String)
        For cHex As Integer = 1 To Len(valHex) Step 2
            Ctx.Response.BinaryWrite(New Byte() {CByte("&H" & Mid(valHex, cHex, 2))})
        Next
    End Sub

    Sub SendBitmap()
        If (ImageWidth Mod 4) <> 0 Then
            BmpEndLine = New String("0", (4 - (ImageWidth Mod 4)) * 2)
        Else
            BmpEndLine = vbNullString
        End If
        Dim BmpInfoHeader() As String = New String() {"28000000", "00000000", "00000000", "0100", "0800", "00000000", "00000000", "120B0000", "120B0000", "00000000", "00000000"}
        BmpInfoHeader(1) = FormatHex(Hex(ImageWidth), 4, 0, True)
        BmpInfoHeader(2) = FormatHex(Hex(ImageHeight), 4, 0, True)
        BmpInfoHeader(6) = FormatHex(Hex((ImageHeight * ImageWidth) + (ImageHeight * (Len(BmpEndLine) / 2))), 4, 0, True)
        BmpInfoHeader(9) = FormatHex(Hex(Len(BmpColorMap) / 8), 4, 0, True)
        BmpInfoHeader(10) = BmpInfoHeader(9)
        Dim BmpHeader() As String = New String() {"424D", "00000000", "0000", "0000", "00000000"}
        BmpHeader(1) = FormatHex(Hex((Len(Join(BmpHeader, "")) / 2) + (Len(Join(BmpInfoHeader, "")) / 2) + (Len(BmpColorMap) / 2) + (ImageHeight * ImageWidth) + (ImageHeight * (Len(BmpEndLine) / 2))), 4, 0, True)
        BmpHeader(4) = FormatHex(Hex((Len(Join(BmpHeader, "")) / 2) + (Len(Join(BmpInfoHeader, "")) / 2) + (Len(BmpColorMap) / 2)), 4, 0, True)

        Ctx.Response.Clear()
        Ctx.Response.Buffer = True
        Ctx.Response.ContentType = "image/bmp"
        Ctx.Response.AddHeader("Content-Disposition", "inline; filename=captcha.bmp")
        Ctx.Response.CacheControl = "no-cache"
        Ctx.Response.AddHeader("Pragma", "no-cache")
        Ctx.Response.Expires = -1

        SendHex(Join(BmpHeader, ""))
        SendHex(Join(BmpInfoHeader, ""))
        SendHex(BmpColorMap)
        For y As Integer = ImageHeight To 1 Step -1
            For x As Integer = 1 To ImageWidth
                Dim tmpHex As String = Bitmap(y, x)
                If tmpHex = vbNullString Then
                    SendHex(BColor)
                Else
                    SendHex(tmpHex)
                End If
            Next
            SendHex(BmpEndLine)
        Next
        Ctx.Response.Flush()
    End Sub

End Class